### ISSUE TITLE
[Enhancement]文字カウント機能の追加

### ISSUE THREAD

**Issue by yakult1995** [yakult1995/kushida#5]
### 30秒毎に発言数カウント
* １人ずつバラバラにカウント
* 何かしらの形式で何処かに保存
  * DBかな？
  * @kussy18 結果画面への表示要る？

**Comment by kussy18** [comment]
結果画面への表示ほしいです

**Comment by yakult1995** [comment]
ごめん！今日作業出来るか怪しいから明日の帰りの新幹線では作業するわ！

**Comment by kussy18** [comment]
忙しいのに、申し訳ない！
1/9までにできればありがたいかな～って感じだから、時間ある時でいいよ！
毎度ありがとう！

**Comment by yakult1995** [comment]
ページリロードとかは一切考慮しなくてもいいよな？
そもそもリロードした時点でチャット出来なくなってるし
